# Generated by Django 5.2.4 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_payment_pay_date_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='created', max_length=20, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe session ID'),
        ),
    ]
